name: Performance test

on:
  workflow_dispatch:

jobs:
  test:
    name: Performance test
    runs-on: X64
    strategy:
      matrix:
        tag: ["gnu", "intel"]
    container: ghcr.io/deepmodeling/abacus-${{ matrix.tag }}
    timeout-minutes: 2880
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Requirements
        run: |
          apt install -y time
      - name: Test
        run: |
          . /opt/intel/oneapi/setvars.sh || :
          cd tests/performance/
          bash run.sh
      - name: Show Result
        if: always()
        run: |
          cat tests/performance/sumall.dat
